Map[
  Function[
    BeginPackage[
      FileBaseName[DirectoryName@$InputFileName]<>"`"<>#<>"`",
      FileBaseName[DirectoryName@$InputFileName]<>"`"
      ];
    EndPackage[]
    ],
  {
    "Paclets",
    "Utilities",
    "Formatting",
    "FrontEnd",
    "Frameworks",
    "External",
    "Web"
    }
  ]

FrontEnd`Private`GetUpdatedSymbolContexts[]
