{
  "bootstrap.css",
  "font-awesome.css",
  "https://fonts.googleapis.com/css?family=Source+Code+Pro",
  "https://reference.wolfram.com/language-assets/css/special-styles.css",
  "https://www.w3schools.com/w3css/4/w3.css",
  "common.css",
  "style.css"
  }
