With[{
  tempArgs=
    $$templateLib["getTemplateArguments"][#]
  },
  !MatchQ[
    $$templateLib["templateArgumentLookup"][tempArgs,"var"],
    _Missing|False|None|_String?(StringMatchQ[Whitespace])
    ]
  ]&
