{
  <|
    "href"->"pages/about.html",
    "body"->"About"
    |>,
  Replace[$$templateLib["getTemplateArguments"][#]["PacletsURL"],{
    s_String:>
      <|
        "href"->s,
        "body"->"Paclets"
        |>,
    _->Nothing
    }],
  Replace[$$templateLib["getTemplateArguments"][#]["GitHubUserName"],{
    s:_String|{__String}:>
      <|
        "href"->
          URLBuild@<|
            "Scheme"->"https",
            "Domain"->"github.com",
            "Path"->Flatten@{s}
            |>,
        "body"->"GitHub"
        |>,
    _->Nothing
    }]
  }&
