{
  <|
    "href"->"pages/about.html",
    "body"->"About"
    |>,
  <|
    "href"->"categories.html",
    "body"->"Categories"
    |>,
  <|
    "href"->"tags.html",
    "body"->"Tags"
    |>,
  <|
    "href"->"authors.html",
    "body"->"Authors"
    |>,
  Replace[Templating`$TemplateArguments["DocumentationURL"],{
    s_String:>
      <|
        "href"->s,
        "body"->"Documentation"
        |>
    }]
  }
