(* ::Package:: *)

(* ::Title:: *)
(*$Name`*)


(* ::Text::GrayLevel[0.5]:: *)
(* Autogenerated $Name loader file *)


BeginPackage["$Name`"];


(* ::Section:: *)
(* Package Functions *)


Begin["`Private`Package`"];
$InitCode


(* ::Subsection::Closed:: *)
(* End[] *)


End[];


(* ::Section:: *)
(* Load *)


CheckAbort[
	`Private`Package`appLoad[],
	EndPackage[]
	];
EndPackage[];
