(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



BeginPackage["$CuratedData`"];


$CuratedData::usage=
	"An wrapper to the other DataPaclets";


Begin["DataPaclets`$CuratedDataDump`"];


$DataFunctions=
	$CuratedDataFunctions;


If[!AssociationQ@$DataFunctionsLoaded,
	$DataFunctionsLoaded=<||>
	];


$CuratedData["DataFunctions"]=
	$DataFunctions;


$CuratedData[data_?(KeyMemberQ[$DataFunctions,#]&),"DataFunction"]:=
	(
		If[!TrueQ@Lookup[$DataFunctionsLoaded,$DataFunctions[data],False],
			With[{functionName=SymbolName[$DataFunctions[data]]},
				If[Length@PacletManager`PacletFind[functionName]===0,
					PacletManager`PacletInstall[functionName];
					];
				If[Length@DownValues@Evaluate@$DataFunctions[data]===0,
					Get[functionName<>"`"]
					];
				$DataFunctionsLoaded[$DataFunctions[data]]=True
				]
			];
		$DataFunctions[data]
		);
$CuratedData[data_?(KeyMemberQ[$DataFunctions,#]&),args___]:=
	$CuratedData[data,"DataFunction"][args];
$CuratedData[]:=
	Values@$DataFunctions;


End[];


EndPackage[];



